# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-02 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180502_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('workclass', models.TextField(blank=True, null=True)),
                ('fnlwgt', models.IntegerField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('education_num', models.TextField(blank=True, null=True)),
                ('martial_status', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('relationship', models.TextField(blank=True, null=True)),
                ('race', models.TextField(blank=True, null=True)),
                ('sex', models.TextField(blank=True, null=True)),
                ('capital_gain', models.IntegerField(blank=True, null=True)),
                ('capital_loss', models.IntegerField(blank=True, null=True)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('native_country', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Adult',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='myapp_adult',
        ),
    ]
